version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: muhammadsheraza002/startups-backend:latest
    container_name: startup-query-agent-api
    ports:
      - "8000:8000"
    environment:
      - CHATOOLOMA_MODEL=llama3.2

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: muhammadsheraza002/startups-frontend:latest
    container_name: startup-query-agent-frointend
    ports:
      - "8501:8501"
    depends_on:
      - backend
